RootstockCollective/dao-frontend

src/app/proposals/LatestProposalsTable.tsx
src/app/proposals/ProposalNameColumn.tsx
src/app/proposals/ProposalsContext.tsx
src/app/proposals/SentimentColumn.tsx
src/app/proposals/SharedProposalsTableContext.tsx
src/app/proposals/StatusColumn.tsx
src/app/proposals/TimeRemainingColumn.tsx
src/app/proposals/VotesColumn.tsx
src/app/proposals/hooks/useGetProposalDeadline.ts
src/app/proposals/shared/utils.ts
src/shared/hooks/useProposalState.ts
src/shared/hooks/useVoteOnProposal.ts

feat: Revamped proposals to use context.
feat: Reduced api calls to backend.
feat: Separated each column into its own file.
feat: separated proposal state into its own hook.
fix: added refetch interval to voteOnProposal to avoid unnecessary calls to node

DAO-720 feat: Implemented Time Remaining Column.

---

src/pages/proposals/[id].tsx

DAO-689 Added white-space css rule to account for new line.

---

src/app/globals.css
src/app/treasury/MetricsSection.tsx
src/app/treasury/TotalTokenHoldingsSection.tsx
src/app/treasury/TreasurySection.tsx
src/components/Button/Button.tsx
src/components/Button/DivWithGradient.tsx
src/components/Button/types.ts
src/components/GradientHeader/GradientHeader.tsx
src/components/Header/Header.tsx
src/components/LeftSidebar/LeftSidebar.tsx
src/components/LeftSidebar/SidebarButtons.tsx
src/components/LeftSidebar/UsefulLinks.tsx
src/components/LeftSidebar/types.ts
src/components/MainContainer/MainContainer.tsx
src/components/MainContainer/StatefulSidebar.tsx
src/components/MetricsCard/MetricsCard.tsx
src/components/Table/Table.tsx

Dao 717 Implemented gradient

---

src/app/proposals/LatestProposalsTable.tsx
src/app/proposals/VotesColumn.tsx

DAO-721: fix: will count for, abstain vote only.

---

src/app/treasury/MetricsSection.tsx

Dao xxx strif treasury

---

package-lock.json
package.json
src/pages/proposals/create.tsx

Reverts RootstockCollective/dao-frontend#258

Revert "Remove legacy rsk-utils package"

---

src/app/user/Balances/hooks/useGetAddressTokens.ts

In order make the issue reproducible, it's necessary to block the request to node url.

DAO-767: [Obscure defect] to lower case message is displayed 

---

src/lib/endpoints.ts

This is to avoid recurring offline explanations of what that hardcoded value is. Is this enough?

Create a const for proposal created event

---

next.config.mjs

ci(dev): disable proxy configuration

---

src/app/treasury/HoldersSection.tsx

Updates the icons from a static image to use the dynamic images.

Update holder icon to use the jdenticon similar to the connection box.

---

src/app/treasury/TreasuryContext.tsx
src/app/treasury/TreasurySection.tsx
src/lib/contracts.ts

This PR addresses this jira [ticket](https://rsklabs.atlassian.net/browse/DAO-737)
Current Render

chore: change column order on treasury page

---

src/components/ErrorPage/ErrorBoundary.tsx
src/components/ErrorPage/commonErrors.ts

Show a more friendly error when we can decipher them. This code can be a starting point for errors that we get that are more common.

DAO-798 Create starting point for more friendly errors.

---

src/app/communities/NftHoldersSection.tsx
src/app/treasury/HoldersSection.tsx
src/components/ErrorMessageAlert/ErrorMessageAlert.tsx

For now, until Roger makes a design for it.

DAO-XXX Implemented error message alert when fetching fails

---

src/app/treasury/HoldersSection.tsx

DAO-XXX Remove decimals from holders token table

---

src/app/proposals/VotesColumn.tsx

DAO-797: Rouding voting power

---

src/app/proposals/TimeRemainingColumn.tsx
src/app/proposals/hooks/useGetProposalDeadline.ts

Fixes issue described on #266.

Fix conditional hooks

---

src/components/GradientHeader/GradientHeader.tsx
src/components/LeftSidebar/LeftSidebar.tsx
src/components/LeftSidebar/SidebarButtons.tsx
src/components/MainContainer/MainContainer.tsx

This PR addresses this jira [ticket](https://rsklabs.atlassian.net/browse/DAO-769)
Current Render
Render for smaller screens

fix: make left bottom info in left side bar fixed and sticky

---

src/app/providers/ContextProviders.tsx
src/shared/context/FeatureFlagContext.tsx

Adds a feature flag system
To allow incremental delivery and feature-based testing, A/B testing, easier QA testing, linear history, less conflicting releases, ...

feat(dao): add feature flags

---

src/shared/hooks/useFetchNftHolders.ts

fix: make table results render 12 items for uniformity

---

src/app/user/Delegation/DelegationSection.tsx
src/app/user/Delegation/ReclaimCell.tsx
src/app/user/Delegation/hooks/useDelegateToAddress.tsx
src/app/user/Delegation/type.ts
src/shared/txMessages.ts

DAO-819: As a user I need to reclaim the delegation of my stRIF (delegate back to myself)

---

src/pages/communities/nft/[address].tsx

Fixes this https://github.com/RootstockCollective/dao-frontend/security/code-scanning/2

fix log injection

---

src/app/collective-rewards/allocations/AllocationAmount.tsx
src/app/collective-rewards/allocations/AllocationMetrics.tsx
src/app/collective-rewards/allocations/Header.tsx
src/app/collective-rewards/allocations/page.tsx
src/app/collective-rewards/allocations/useBackerTotalAllocation.tsx
src/components/Input/Input.tsx

- structure the page layout
- add the metrics

TOK-477: page layout and metrics

---

tailwind.config.ts

- change the collapsible animation to show the content gradually

fix(Collapsible): fix opacity to gradually show the component

---

src/app/treasury/TreasuryContext.tsx
src/app/treasury/TreasurySection.tsx
src/lib/contracts.ts

Changed the variable treasuryContracts from an array to an object.

Request to resolve #301

---

src/app/proposals/page.tsx

chore: update tooltip explainer for voting power

---

src/components/DebounceSearch/DebounceSearch.tsx
src/components/Input/Input.tsx

Implement a dual debounce mechanism in the DebounceSearch component to enhance user experience by displaying a spinner when the user stops typing and hiding it before finalizing the search input.

Show spinner during debounce in search component

---

src/lib/abis/StRIFTokenAbi.ts

With the upgrade of the stRIF contract, this PR updates the ABI to v2.

Update the stRIF ABI to version 2

---

src/app/proposals/LatestProposalsTable.tsx
src/components/Modal/Modal.tsx

Display a message when no proposals are available in the Latest Proposals table.

Add message for no proposals found in LatestProposalsTable

---

src/app/collective-rewards/active-builders/ActiveBuildersContent.tsx
src/app/collective-rewards/active-builders/ActiveBuildersGrid.tsx
src/app/collective-rewards/active-builders/ActiveBuildersGridItem.tsx
src/app/collective-rewards/leaderboard/BuildersLeaderBoardTable.tsx
src/app/collective-rewards/rewards/backers/hooks/useGetBackerRewards.ts
src/app/collective-rewards/shared/context/SearchContext.tsx
src/app/collective-rewards/user/components/Button/BecomeABuilderButton.tsx
src/app/collective-rewards/utils/index.ts

refactor: search context

---

src/app/collective-rewards/leaderboard/BuildersLeaderBoardTable.tsx
src/app/collective-rewards/metrics/AllTimeRewardsMetrics.tsx
src/app/collective-rewards/rewards/backers/AllTimeShare.tsx
src/app/collective-rewards/rewards/backers/BackerRewardsTable.tsx
src/app/collective-rewards/rewards/backers/Rewards.tsx
src/app/collective-rewards/rewards/backers/RewardsCard.tsx
src/app/collective-rewards/rewards/builders/AllTimeRewards.tsx
src/app/collective-rewards/rewards/builders/AllTimeShare.tsx
src/app/collective-rewards/rewards/builders/EstimatedRewards.tsx

fix: add the missing tooltips

---

src/app/collective-rewards/rewards/builders/hooks/useGetRewardPercentageToApply.ts
src/app/collective-rewards/settings/builder/BuilderRewardsSettingsMetrics.tsx
src/app/collective-rewards/settings/builder/context/BuilderSettingsContext.tsx

-  show the current percentage if cooldown expired

TOK-494: show the current pct if remaining time has passed

---

src/lib/contracts.ts

##
- update growth rewards bucket address

TOK-493: update growth rewards bucket address

---

src/app/collective-rewards/rewards/MyRewards.tsx
src/app/collective-rewards/rewards/components/Section/RewardsSectionHeader.tsx

- update text description in MyRewards section

TOK-495: update the text in my rewards section

---

src/pages/proposals/[id].tsx

- show decode input dewhitelist proposal

fix: show the decoded input for dewhitelist proposals

---

src/app/collective-rewards/rewards/utils/formatMetrics.test.ts
src/app/collective-rewards/rewards/utils/formatMetrics.ts

fix: formatOnChain franction

---

src/app/proposals/create/TreasuryWithdrawProposalForm.tsx
src/app/proposals/shared/utils.ts
src/app/user/Delegation/DelegateModal.tsx

Checksum validation for address in delegate and proposal views.

DAO-844: add checksum validation

---

src/pages/communities/nft/[address].tsx

This PR fixes this jira [ticket](https://rsklabs.atlassian.net/browse/DAO-807)
User with no stRIF
User with sufficient stRIF

fix: fix issue where user is able to attempt to claim nft when they have no balance

---

src/app/collective-rewards/active-builders/ActiveBuildersGridItem.tsx
src/app/collective-rewards/allocations/components/BuilderAllocationHeader.tsx
src/app/collective-rewards/shared/components/Table/TableCells.tsx
src/app/collective-rewards/utils/isBuilderOperational.ts

[TOK-526](https://rsklabs.atlassian.net/browse/TOK-526)

TOK-526: proposal joined date

---

src/app/proposals/create/RemoveBuilderProposalForm.tsx
src/app/proposals/hooks/useRemoveBuilderProposal.ts
src/app/proposals/shared/errors.ts

[TOK-360](https://rsklabs.atlassian.net/browse/TOK-360)

TOK-360: builder dewhitelist validation

---

src/app/collective-rewards/shared/components/Table/TableCells.tsx

- fix missing `isBuilderOperational` import
- remove unused imports
- build is failing

build: fix missing import

---

src/app/proposals/create/TreasuryWithdrawProposalForm.tsx
src/app/proposals/page.tsx
src/app/user/Balances/RenderTotalBalance.tsx
src/app/user/Delegation/TokenValue.tsx
src/app/user/Stake/StakePreview.tsx
src/app/user/Stake/StakePreviewBalance.tsx
src/components/TokenImage/TokenImage.tsx
src/components/TokenImage/index.ts

DAO-849: Add token icons and USD to tables

---

src/components/Modal/ConnectWalletModal.tsx

DAO-918: Connect popup still has the old Icon

---

src/components/MainContainer/MainContainer.tsx

[TOK-532](https://rsklabs.atlassian.net/browse/TOK-532)

TOK-532/misplaced-bottom-links

---

src/app/collective-rewards/metrics/TotalActiveBuildersMetrics.tsx

[TOK-529](https://rsklabs.atlassian.net/browse/TOK-529)

TOK-529: Active builder metric displays total gauges length

---

src/app/communities/communityUtils.tsx
src/pages/communities/nft/[address].tsx
src/shared/hooks/useCommunity.ts
src/shared/types.ts

DAO-934: Invalid generic message when the user hasn't voted 

---

src/app/communities/communityUtils.tsx
src/pages/communities/nft/[address].tsx
src/shared/hooks/useCommunity.ts
src/shared/types.ts

DAO-935: Vanguard NFT wave complete error message missing 

---

src/app/collective-rewards/active-builders/ActiveBuildersContent.tsx
src/app/collective-rewards/allocations/components/BuilderAllocationHeader.tsx
src/app/collective-rewards/shared/components/Pagination.tsx
src/app/collective-rewards/shared/components/Table/TableCells.tsx
src/app/collective-rewards/shared/context/PaginatedDataContext.tsx
src/app/collective-rewards/shared/context/index.ts
src/app/collective-rewards/user/components/Button/BecomeABuilderButton.test.tsx
src/app/collective-rewards/user/components/Button/BecomeABuilderButton.tsx
src/app/collective-rewards/utils/isBuilderOperational.ts
src/components/Address/withCopy.tsx
src/components/Modal/BecomeABuilderModal.tsx

[TOK-383](https://rsklabs.atlassian.net/browse/TOK-383)

TOK-383: in-progress-submit-kyc

---

src/app/collective-rewards/shared/components/CRWhitepaperLink.tsx

TOK-547: update CR whitepaper link

---

src/app/proposals/LatestProposalsTable.tsx

This PR addresses this jira [ticket](https://rsklabs.atlassian.net/browse/DAO-549)
Current Render

feat: implement table pagination

---

.github/dependabot.yml
.github/workflows/build.yaml
.github/workflows/codeql.yml
.github/workflows/cr.qa.deploy.yaml
.github/workflows/cr.staging.deploy.yaml
.github/workflows/dependency_review.yml
.github/workflows/dev.deploy.yaml
.github/workflows/e2e.yml
.github/workflows/lint.yml
.github/workflows/mainnet.deploy.yaml
.github/workflows/staging.deploy.yaml
.github/workflows/storybook.yml
.github/workflows/testnet.deploy.yaml
.github/workflows/unit-tests.yml
Dockerfile
src/app/communities/communityUtils.tsx
src/app/proposals/create/TreasuryWithdrawProposalForm.tsx
src/lib/utils.ts

Fixes issues found by OSS scorecard

Scorecard fixes

---

src/app/proposals/page.tsx
src/app/proposals/table-columns/VotesColumn.tsx
src/app/treasury/HoldersSection.tsx
src/app/treasury/TokenHoldings.tsx
src/app/treasury/TokenHoldingsStRIF.tsx
src/app/user/Balances/RenderTotalBalance.tsx
src/app/user/Delegation/TokenValue.tsx
src/app/user/Stake/StakePreviewBalance.tsx
src/app/user/Stake/Steps/StepOne.tsx
src/components/MetricsCard/MetricsCard.tsx
src/components/Modal/VoteProposalModal.tsx
src/lib/utils.ts
src/pages/proposals/[id].tsx

Add missing commas in numbers

---

src/lib/constants.ts

Fix issue with incorrect GTM id

chore: correct tag id

---

src/pages/communities/nft/[address].tsx

DAO-959: show how many NFTs are left to claim

---

src/pages/proposals/[id].tsx

format amount with commas

---

src/components/LeftSidebar/UsefulLinks.tsx
src/components/LeftSidebar/links.tsx

@Freshenext mentioned something about react-icons. What are we changing them for? Cause I believe `External Link` component is using the library.

refactor: useful icons GET RIF and GET RBTC

---

src/pages/proposals/[id].tsx
src/shared/txMessages.ts

DAO-957: show a more precise error message

---

src/app/collective-rewards/rewards/builders/hooks/useGetBuildersRewards.ts
src/app/collective-rewards/rewards/utils/getBackerRewardPercentage.test.ts
src/app/collective-rewards/shared/components/Table/TableCells.test.tsx
src/app/collective-rewards/shared/components/Table/TableCells.tsx

[TOK-571](https://rsklabs.atlassian.net/browse/TOK-571)

TOK-571/backer-rewards-pct-consistency

---

src/app/collective-rewards/leaderboard/BuilderLeaderBoard.tsx
src/app/collective-rewards/shared/hooks/index.ts
src/app/collective-rewards/shared/hooks/useReadBackersManager.ts
src/components/Popover/Popover.tsx

https://rsklabs.atlassian.net/browse/TOK-488

TOK-488: block allocs in distribution

---

.env.testnet.qa

- change the QA configuration environment
- to enable CORS bypass
- to point to the current URL

Fix: QA env

---

src/app/collective-rewards/settings/builder/BuilderRewardsSettingsForm.tsx

[TOK-585](https://rsklabs.atlassian.net/browse/TOK-585)

TOK-585/percentage-no-decimals

---

src/app/proposals/create/CreateBuilderProposalForm.tsx
src/app/proposals/create/CreateProposalHeaderSection.tsx
src/app/proposals/create/RemoveBuilderProposalForm.tsx
src/app/proposals/create/TreasuryWithdrawProposalForm.tsx

This PR fixes this jira [ticket](https://rsklabs.atlassian.net/browse/DAO-975)

feat: include proposal type to title

---

src/pages/proposals/[id].tsx
src/shared/hooks/useExecuteProposal.ts

Somehow `useWaitForTransactionReceipt` cannot be used along with `waitForTransactionReceipt`.

DAO-1010: Fix Execute button doesn't refresh

---

package-lock.json
package.json

[TOK-594](https://rsklabs.atlassian.net/browse/TOK-594)

TOK-594/viem-update

---

src/app/user/Balances/StakeRIFCell.tsx
src/app/user/Balances/UnStakeRIFCell.tsx

DAO-1007: Adjust button width

---

src/app/proposals/[id]/page.tsx
src/components/Popover/Popover.tsx

DAO-925: Change user cannot vote text

---

src/app/proposals/choose/components/card/card.tsx
src/app/proposals/choose/components/card/data.tsx
src/app/proposals/choose/components/info-panel/data.tsx
src/app/proposals/choose/components/info-panel/info-panel.tsx

- Update card titles and descriptions to enhance clarity  
[DAO-1026](https://rsklabs.atlassian.net/browse/DAO-1026)

Improve card titles and descriptions 

---

src/app/collective-rewards/leaderboard/BuildersLeaderBoardTable.tsx
src/app/collective-rewards/rewards/backers/BackerRewardsTable.tsx
src/app/collective-rewards/rewards/types.ts
src/app/collective-rewards/utils/getCombinedFiatAmount.ts

Pending testing to verify it works, waiting for reply in the slack channel from @Ken-li-iov

refactor: using Big instead of number getCombinedFiatAmount

---

src/app/proposals/components/LatestProposalsTable.tsx
src/components/DebounceSearch/DebounceSearch.tsx
src/lib/constants.ts

This PR addresses this jira [ticket](https://rsklabs.atlassian.net/browse/DAO-931)
Current Renders

feat: implement proposal list quick filter

---

src/app/proposals/choose/components/card/data.tsx
src/app/proposals/choose/components/info-panel/data.tsx

- Change some text in Choose Your Proposal page components
Request from product
[DAO-1026](https://rsklabs.atlassian.net/browse/DAO-1026)

Update titles and descriptions  in Choose Your Proposal card and info panel components

---

src/config/config.ts

- configure batch size
- RSKj max requests per batch is 100
- [wagmi batch size](https://wagmi.sh/core/api/transports/http#batch-batchsize)
- [rskj configuration](https://github.com/rsksmart/rskj/blob/master/rskj-core/src/main/resources/reference.conf#L394)

TOK-594: set batch size

---

src/app/proposals/components/LatestProposalsTable.tsx
src/lib/constants.ts

Addresses enhancements added to this jira [ticket](https://rsklabs.atlassian.net/browse/DAO-931)
Current Render

refactor: implement enhancements

---

src/app/user/Delegation/DelegationSection.tsx

DAO-1007: fix button position

---

src/app/user/Delegation/DelegationSection.tsx

DAO-1007: fix button width

---

src/app/proposals/choose/components/card/data.tsx
src/app/proposals/choose/components/example-card/data.tsx
src/app/proposals/choose/components/info-panel/arrow-link.tsx
src/app/proposals/choose/components/info-panel/data.tsx
src/app/proposals/choose/components/info-panel/deactivation-footer.tsx
src/app/proposals/choose/components/info-panel/icons/arrow-icon.tsx
src/app/proposals/choose/components/info-panel/icons/link-arrow.tsx
src/app/proposals/choose/components/info-panel/info-panel.tsx
src/app/proposals/choose/page.tsx
src/app/proposals/choose/types.ts

- Revise the text in the info panel (see Ref)
- Improve the LinkArrow component's layout to prevent line breaks, ensuring a better visual presentation
Before:
After:
[DAO-1044](https://rsklabs.atlassian.net/browse/DAO-1044)

Update info panel text and enhance LinkArrow component layout

---

src/app/proposals/create/RemoveBuilderProposalForm.tsx
src/app/proposals/create/TreasuryWithdrawProposalForm.tsx
src/components/Form/Form.stories.tsx

We're displaying the word proposal too many times.

DAO-1021: [Enhancement] Remove proposal from the label

---

src/app/user/Balances/RenderTotalBalance.tsx
src/lib/big.ts

DAO-1041: Reduce decimals on RIF balance to 0 decimal places

---

src/app/treasury/TreasurySection.tsx
src/components/MetricsCard/MetricsCard.tsx

Fix UI amount on Treasures

---

src/app/communities/communityUtils.tsx

Ticket: [DAO-1033](https://rsklabs.atlassian.net/browse/DAO-1033?atlOrigin=eyJpIjoiYjBlODhkY2RiZTI5NDcwYmE1YTM3YmFmMWMwMGNmODYiLCJwIjoiaiJ9)

DAO-1033: Change text and description on the OG Contributor's NFT page

---

src/app/communities/communityUtils.tsx

Ticket: [DAO-1055](https://rsklabs.atlassian.net/browse/DAO-1055)

DAO-1055: Update NFT badge date details in UI (various)

---

src/app/proposals/components/LatestProposalsTable.tsx

This PR addresses this [defect](https://rsklabs.atlassian.net/browse/DAO-1046)

fix: reset pagination to page one after every filter

---

src/app/collective-rewards/rewards/utils/formatter.test.ts
src/app/collective-rewards/rewards/utils/formatter.ts

https://rsklabs.atlassian.net/browse/DAO-1002
Refactor to use big.js for math operations in utils/formatter.ts

DAO-1002: feat(precision) using big.js for math operations

---

package-lock.json
package.json
src/app/collective-rewards/rewards/MyRewards.tsx
src/app/collective-rewards/rewards/backers/BackerRewardsTable.tsx
src/app/collective-rewards/rewards/backers/Rewards.tsx
src/app/collective-rewards/rewards/backers/context/BackerRewardsContex.tsx
src/app/collective-rewards/rewards/backers/hooks/useGetBackerRewards.ts
src/app/collective-rewards/rewards/builders/Rewards.tsx
src/app/collective-rewards/rewards/components/Section/RewardsSectionHeader.tsx
src/app/collective-rewards/shared/components/Table/TableCells.tsx
src/app/collective-rewards/shared/components/Table/TableHeaders.tsx
src/app/collective-rewards/shared/context/SearchContext.tsx
src/app/collective-rewards/types.ts
src/components/Switch/Switch.stories.tsx
src/components/Switch/Switch.tsx
src/components/Switch/index.ts

[TOK-569](https://rsklabs.atlassian.net/browse/TOK-569)

TOK-559: simplify-my-rewards

---

src/app/collective-rewards/user/components/Button/WithBuilderButton.tsx
src/app/shared/components/NFTBoosterCard/NFTBoosterCard.stories.tsx
src/app/shared/components/NFTBoosterCard/NFTBoosterCard.tsx
src/app/shared/components/index.ts

[Task](https://rsklabs.atlassian.net/browse/TOK-617)

TOK-617: add nft boost status card

---

src/components/LeftSidebar/links.tsx
src/components/dropdown/data.tsx

I'm aware of the duplicate code and links here. For the sake of the release, we can do that at the next iteration. 
Fixes:

Add link for staking RIF

---

src/app/collective-rewards/leaderboard/BuildersLeaderBoardTable.tsx
src/app/collective-rewards/rewards/MyRewards.tsx
src/app/collective-rewards/rewards/backers/BackerRewardsTable.tsx
src/app/collective-rewards/shared/components/Table/TableCells.test.tsx
src/app/collective-rewards/shared/components/Table/TableCells.tsx
src/app/collective-rewards/shared/components/Table/TableHeaders.tsx

[TOK-632](https://rsklabs.atlassian.net/browse/TOK-632)

TOK-632: table-simplification

---

src/app/collective-rewards/user/components/Button/BecomeABuilderButton.tsx
src/app/proposals/components/HeaderSection.tsx
src/components/Button/HeaderButton.tsx
src/components/Button/index.ts
src/components/Tabs/Tabs.tsx

Abstracts the header button
[TOK Task](https://rsklabs.atlassian.net/browse/TOK-639)
[DAO Task](https://rsklabs.atlassian.net/browse/DAO-1081)

TOK-639: unify header button size

---

src/app/communities/nft/[address]/page.tsx
src/app/providers/NFT/BoosterContext.test.tsx
src/app/providers/NFT/BoosterContext.tsx
src/app/shared/components/NFTBoosterCard/NFTBoosterCard.tsx
src/app/shared/components/NFTBoosterCard/SelfContainedNFTBoosterCard.tsx

[TOK-637](https://rsklabs.atlassian.net/browse/TOK-637)

TOK-637: lowercase addresses

---

src/app/user/Stake/StakingContext.tsx

Ticket [DAO-1076](https://rsklabs.atlassian.net/browse/DAO-1076?atlOrigin=eyJpIjoiNDU3MDI0YmU1NzEwNDNkOThkMmY0OGU2YTdiYjJlNTYiLCJwIjoiaiJ9).

DAO-1076: Fix decimal places on staking

---

src/app/user/Balances/context/BalancesContext.tsx
src/app/user/Balances/hooks/useGetAddressBalances.ts
src/app/user/Balances/hooks/useGetAddressTokens.ts
src/app/user/page.tsx
src/components/dropdown/data.tsx

I've made all the Enhancement except:
- "Sing posting should be right next to “My rewards” like the Figma (now is a bit centered)" -  because of the future design change, it doesn't make sense to refactor the positioning and spend time as it will be a completely different component with no buttons and title next to it, in the completely different position.

refactor: Signposting to address enhancements comments

---

src/app/communities/CommunityItem.tsx
src/app/communities/components/BoostedBox.tsx
src/app/communities/components/BoostedLabel.tsx
src/app/communities/hooks/useIsBoosted.ts
src/app/communities/page.tsx

Transform the communities page into a server component, enhancing performance and maintainability. Introduce client components for dynamic features like boosted state highlighting.
Required by the following ticket
[DAO-1100](https://rsklabs.atlassian.net/browse/DAO-1100)

Refactor communities page to use server components

---

.github/workflows/staging.deploy.yaml

Reverts RootstockCollective/dao-frontend#703

Revert "Update staging.deploy.yaml"

---

src/app/communities/communityUtils.tsx

Change communities description
Requested by the ticket [DAO-1108](https://rsklabs.atlassian.net/browse/DAO-1108)

chore: change communities description

---

src/app/user/Communities/CommunitiesSection.tsx
src/app/user/Communities/CommunityCard.tsx
src/app/user/types.ts

Shows the campaign card glowing with bolt icon on user's my holdings page for all active campaigns
Resolves:
[Task](https://rsklabs.atlassian.net/browse/TOK-647)

TOK-647: glow active campaign user page

---

src/app/proposals/[id]/page.tsx

Address bug in this Jira [ticket](https://rsklabs.atlassian.net/browse/DAO-1121)

fix: fix issue where usd value is not rendered for rbtc

---

src/app/collective-rewards/rewards/backers/Rewards.tsx

[TOK-659](https://rsklabs.atlassian.net/browse/TOK-659)

TOK-659/estimated-rewards-tooltip

---

src/app/user/Stake/Steps/StepOne.tsx

This PR fixes the bug reported in this [ticket](https://rsklabs.atlassian.net/browse/DAO-1138)

fix: fix issue with 100% unstaking for more more arbitatry decimal places

---

src/shared/walletConnection/components/topPageHeader/TopPageHeader.tsx

animate header become builder button

feat: animate header become builder button

---

src/components/Tabs/Tabs.tsx

update my collective tabs design
[Jira](https://rsklabs.atlassian.net/jira/software/projects/TOK/boards/267?assignee=712020%3A42dabdd3-0b32-4060-be21-62cfd46a1751&selectedIssue=TOK-646)

TOK-646: update my collective tabs design

---

src/app/proposals/components/LatestProposalsTable.tsx
src/app/proposals/components/table-columns/CategoryColumn.tsx
src/app/proposals/components/table-columns/ProposalNameColumn.tsx
src/app/proposals/hooks/useProposalListData.ts
src/app/proposals/hooks/useVotingPower.ts
src/app/proposals/page.tsx
src/components/Category/Category.tsx
src/components/Category/types.ts

[DAO-1124](https://rsklabs.atlassian.net/browse/DAO-1124)
- Adding create proposal at header level
- Adding Delegated Voting Power card
- Adding Active proposal for voting card
- Adding Category column to the Latest Proposal Page
- Adding ArrowIcon in Proposal Name

DAO-1124: proposal list page

---

src/lib/constants.ts

This PR addresses this [ticket](https://rsklabs.atlassian.net/browse/DAO-1154)
New Render

feat: add new proposal new filter

---

src/app/collective-rewards/rewards/MyRewards.tsx

fix: loading state in my rewards

---

src/shared/walletConnection/components/topPageHeader/TopPageHeader.tsx

- always show builder button when user is connected

fix: always show builder button when user is connected

---

src/app/communities/communityUtils.tsx

Shorten EA NFT description text even more

---

src/app/treasury/MetricsSection.tsx
src/app/treasury/TabsSection.tsx
src/app/treasury/hooks/useTabCards.ts
src/app/user/Delegation/DelegationSection.tsx
src/components/MetricsCard/MetricsCard.tsx
src/components/Modal/VoteProposalModal.tsx

Addressed QA issues on the treasury page, replaced question images with a custom icon, and added a tooltip for the TVL metric to improve user experience and clarity.
[Ticket DAO-1110](https://rsklabs.atlassian.net/browse/DAO-1110)

Fix issues on treasury page and enhance metrics display

---

src/app/proposals/hooks/useVotingPower.ts
src/app/proposals/page.tsx

DAO-1124: fix delegated voting power

---

.github/workflows/dev.deploy.yaml

Fix missing space in deployment file

fix: dev deploy file

---

src/components/dropdown/data.tsx
src/components/dropdown/dropdown.tsx

Ticket [DAO-1157](https://rsklabs.atlassian.net/browse/DAO-1157?atlOrigin=eyJpIjoiZWJiODY3NWUwZTM0NGEzZjk2ZGU0NzMxMjAwMjQxMzMiLCJwIjoiaiJ9)

Fix 5 steps to get started

---

src/app/treasury/MetricsSection.tsx
src/app/treasury/TabsSection.tsx

Enhance the styling of MetricsCard components to improve overflow handling and set a minimum width.

Update MetricsCard styles for overflow and minimum width

---

.env.release-candidate
package-lock.json
package.json
src/app/collective-rewards/leaderboard/BuildersLeaderBoardTable.tsx
src/config/config.ts
vitest.config.ts

This PR merges the latest changes from the release tags v1.7.1 and v1.7.2 into develop.

V1.7.2 into develop

---

src/app/proposals/components/LatestProposalsTable.tsx
src/components/Table/StatefulTable.tsx

DAO-1166 Double the width of the proposal name column

---

src/app/communities/communityUtils.tsx
src/app/communities/nft/[address]/page.tsx

This PR addresses this Jira [ticket](https://rsklabs.atlassian.net/browse/DAO-1160)
Current Render (New Discussion Button Added, only for Beta Builders NFT)

feat: impl discussion link on communities page

---

src/app/communities/nft/[address]/_components/HolderColumn.tsx
src/app/communities/nft/[address]/_sections/MembershipNFTSection.tsx
src/app/communities/nft/[address]/_sections/NftHoldersSection.tsx
src/app/user/Communities/CommunityCard.tsx

Introduce the `crossOrigin` attribute to various Image components to enhance CORS handling and ensure proper image loading across different origins.

Add crossOrigin attribute to Image components for improved CORS handling

---

src/app/user/page.tsx

Replaced the previous tab implementation due to glitchy hover behavior and pointer flickering. The new UnderlineTabs component provides smooth animated transitions and underline movement, resulting in a much more polished and pleasant user experience.

Replaced buggy tab behavior with animated UnderlineTabs component for smoother UX

---

.github/workflows/booster-deactivate.yaml
.github/workflows/booster-schedule.yaml
.github/workflows/booster.yaml

- fix code scanning issues
- it should fixes the issues raised in [this PR](https://github.com/RootstockCollective/dao-frontend/pull/880)
- so we can merge develop into main

Fix code scanning issues

---

.github/workflows/booster-deactivate.yaml
.github/workflows/booster-schedule.yaml
.github/workflows/booster.yaml

- set global permissions to read-all
- to avoid code scanning issues

fix: set global permissions read-all

---

package-lock.json
package.json
src/app/collective-rewards/metrics/AllTimeRewardsMetrics.tsx
src/app/collective-rewards/metrics/CycleMetrics.tsx
src/app/collective-rewards/metrics/TotalActiveBuildersMetrics.tsx
src/app/collective-rewards/metrics/TotalAllocationsMetrics.tsx
src/app/collective-rewards/metrics/components/ABIMetrics/ABIMetrics.tsx
src/app/collective-rewards/rewards/backers/ClaimableRewards.tsx
src/app/collective-rewards/rewards/backers/RewardsCard.tsx
src/app/collective-rewards/rewards/builders/AllTimeRewards.tsx
src/app/collective-rewards/rewards/builders/ClaimableRewards.tsx
src/app/collective-rewards/rewards/builders/EstimatedRewards.tsx
src/app/collective-rewards/rewards/builders/LastCycleRewards.tsx
src/app/collective-rewards/user/components/Button/BecomeABuilderButton.tsx
src/components/LoadingSpinner/LoadingSpinner.stories.tsx
src/components/LoadingSpinner/LoadingSpinner.tsx
src/components/LoadingSpinner/index.ts
src/components/LoadingSpinner/withLoadingSpinner.tsx
src/components/Modal/BecomeABuilderModal.tsx
src/components/Modal/Modal.tsx

- fixes modal handling by removing unnecessary internalisation of modal close handling
- disables voting power popup when not desired
Resolves [TOK-714](https://rsklabs.atlassian.net/browse/TOK-714)

fix(cr): use better modal handles

---

src/app/communities/communityUtils.tsx

[DAO-1206](https://rsklabs.atlassian.net/browse/DAO-1206)
Fix hydration error in Community NFT page(h1 inside p tag)

DAO-1206: fix hydration errors for community page

---

src/app/providers/NFT/BoosterContext.test.tsx
src/app/providers/NFT/BoosterContext.tsx
src/app/providers/NFT/boost.utils.ts

Trims the content of the `latest` file in the boost context
Resolves [TOK-715](https://rsklabs.atlassian.net/browse/TOK-715)

TOK-715: trim lastestFile content

---

src/app/providers/ContextProviders.tsx

Disabled WalletConnect integration in the application settings.

DAO-1238 Set enableWalletConnect to false in ContextProviders

---

src/app/user/Stake/UnStakingSteps.tsx

This PR implements fix contained [here](https://github.com/RootstockCollective/dao-frontend/pull/973) for the unstake flow

refactor: use more concise approach for unstake

---

src/app/communities/nft/[address]/_sections/NftHoldersSection.tsx

Fixes an additional edge case for this [PR](https://rsklabs.atlassian.net/browse/DAO-1200)

fix: fix issue causing lag in loading data/incorrect data for holders section

---

src/app/user/Delegation/DelegateModal.tsx

This PR addresses this [ticket](https://rsklabs.atlassian.net/browse/DAO-1257)
New Render(Notice the difference in the text of the title and tooltip text)

chore: rename title and tooltip text

---

src/app/collective-rewards/metrics/CycleMetrics.tsx
src/app/collective-rewards/metrics/TotalActiveBuildersMetrics.tsx
src/app/collective-rewards/metrics/TotalAllocationsMetrics.tsx
src/app/collective-rewards/metrics/components/ABIMetrics/ABIMetrics.tsx
src/app/collective-rewards/user/components/Button/BecomeABuilderButton.tsx
src/components/Modal/BecomeABuilderModal.tsx
src/components/Modal/Modal.tsx

fixes modal handling by removing unnecessary internalisation of modal close handling
disables voting power popup when not desired

fix(cr): use better modal handles (#945)

---

src/app/collective-rewards/allocations/context/AllocationsContext.tsx
src/app/collective-rewards/allocations/hooks/useBuildersWithBackerRewardPercentage.ts
src/app/collective-rewards/rewards/backers/BackerRewardsTable.tsx
src/app/collective-rewards/rewards/backers/context/BackerRewardsContext.tsx
src/app/collective-rewards/rewards/backers/hooks/useGetBackerRewards.ts

- these changes were already released with [this commit](https://github.com/RootstockCollective/dao-frontend/commit/c8767241c7905492582857c9756de608e9920455).

fix(useGetBackerRewards): change gauges list map

---

src/app/user/Delegation/DelegateModal.tsx

Handles an additional spelling change for this [ticket](https://rsklabs.atlassian.net/browse/DAO-1257)

chore: text spelling change

---

src/app/proposals/hooks/useRemoveBuilderProposal.ts

Port the changes from the release branch to main

fix(cr): change target SC addr for dewhitelist

---

.github/workflows/storybook.yml
.storybook/preview-head.html
src/theme/base.css
src/theme/default.css

- Introduce updated color schemes, typography, and system status styles for the upcoming design refresh.
- Included additional background, text, and brand color variables, along with new font definitions in Storybook preview.
- These changes set the foundation for enhanced consistency and aesthetics.

DAO-1233 Add new design system variables for May 2025 update

---

.github/workflows/storybook.yml

Adds the URL and env name to the file to make it easier to find the URL.

Update storybook.yml to add env

---

src/components/ButtonNew/Button.stories.tsx
src/components/ButtonNew/Button.tsx

Ticket: [DAO-1251](https://rsklabs.atlassian.net/browse/DAO-1251?atlOrigin=eyJpIjoiYTY0Y2UxNmQ2NWQ0NDhhOGFkYmViYmI3NDUzNWQyYjIiLCJwIjoiaiJ9)

DAO-1251: Implement new button designs

---

.github/workflows/dao.qa.deploy.yaml

Set name of workflow to DAO

---

public/images/close-button.svg
src/app/user/Stake/StakeInputNew/StakeInput.tsx
src/app/user/Stake/StakeInputNew/index.ts
src/app/user/Stake/StakeRIF.tsx
src/app/user/Stake/Steps/StakeSteps.tsx
src/app/user/Stake/Steps/stepsUtils.tsx
src/components/ButtonNew/Button.tsx
src/components/Icons/CaretRight.tsx
src/components/Input/Input.tsx
src/components/TypographyNew/Label.tsx
src/theme/default.css

DAO-1262: Step 1 of the Staking Flow

---

.env.cr.qa
.env.dao.qa
.env.dev
.env.mainnet
.env.release-candidate

Update the graph URL to handle deployment IDs.

build: update the graphs deployment ids

---

src/app/builders/components/Table/SelectorHeaderCell.stories.tsx
src/app/builders/components/Table/SelectorHeaderCell.tsx
src/app/builders/components/Table/index.ts
src/components/Icons/CheckboxChecked.tsx
src/components/Icons/CheckboxUnchecked.tsx

TOK-763: add selector header cell

---

src/components/TableNew/TableHeaderCell.stories.tsx
src/components/TableNew/TableHeaderCell.tsx
src/components/TableNew/TableHeaderNode.stories.tsx
src/components/TableNew/TableHeaderNode.tsx
src/components/TableNew/index.ts

Adds `TableHeaderCell` and `TableHeaderNode` for building horizontal tables headers

TOK-762: add table headers

---

src/app/backing/BackingPage.tsx
src/app/builders/BuildersPage.tsx
src/app/builders/components/BecomeBuilderBanner/BecomeBuilderBanner.stories.tsx
src/app/collective-rewards/components/components/CallToAction/CallToAction.stories.tsx
src/app/collective-rewards/components/components/CallToAction/CallToAction.tsx
src/components/containers/ActionMetricsContainer.stories.tsx
src/components/containers/ActionMetricsContainer.tsx
src/components/containers/ActionsContainer.stories.tsx
src/components/containers/ActionsContainer.tsx
src/components/containers/InfoContainer.stories.tsx
src/components/containers/InfoContainer.tsx
src/components/containers/MetricsContainer.stories.tsx
src/components/containers/MetricsContainer.tsx
src/theme/design_v3.css

[TOK-773](https://rsklabs.atlassian.net/browse/TOK-773)

TOK-773/collective-rewards-ctas-container

---

src/app/builders/BuilderFilterDropdown.stories.tsx
src/app/builders/BuilderFilterDropdown.tsx
src/app/builders/components/MultipleSelectDropdown/MultipleSelectDropdown.stories.tsx
src/app/builders/components/MultipleSelectDropdown/MultipleSelectDropdown.tsx
src/app/builders/components/MultipleSelectDropdown/MultipleSelectDropdownItem.stories.tsx
src/app/builders/components/MultipleSelectDropdown/MultipleSelectDropdownItem.tsx
src/app/builders/components/MultipleSelectDropdown/index.ts
src/app/builders/components/TableColumnDropdown.tsx
src/components/SingleSelectDropdown/SingleSelectDropdown.stories.tsx
src/components/SingleSelectDropdown/SingleSelectDropdown.tsx

Table filter
Added a `SingleSelectDropdown` general component, and the component using it to filter the rows from the table. Has dummy data for now, as the filter names are still in discussion. It does not interact with the table context directly, as the filtering will be done outside of it, as it involves refetch data.

Tok 771/table filter

---

src/app/backing/BackingPage.tsx
src/app/backing/components/BackingInfoTitle/BackingInfoTitle.stories.tsx
src/app/backing/components/BackingInfoTitle/BackingInfoTitle.tsx
src/app/backing/components/BackingInfoTitle/BackingInfoTitleControl.tsx
src/app/backing/components/BackingInfoTitle/index.ts
src/app/backing/components/DottedUnderlineLabel/DottedUnderlineLabel.stories.tsx
src/app/backing/components/DottedUnderlineLabel/DottedUnderlineLabel.tsx
src/app/backing/components/Metrics/EstimatedRewardsMetric.tsx
src/app/backing/components/Popovers/EstimatedRewardsPopover.tsx
src/app/backing/components/RewardsInfo/RewardsInfo.tsx
src/app/builders/BuilderFilterDropdown.tsx
src/components/containers/MetricsContainer.tsx

- Fix top-right metrics according to designs
- Ensure all USD currency codes have underline & rif rbtc popover
- dynamic Backing info title
[Jira ticket](https://rsklabs.atlassian.net/jira/software/projects/TOK/boards/267?selectedIssue=TOK-743)

Tok 743/connected backing page

---

.env.dao.qa
.env.dev
.env.release-candidate

Update the graph deployment ids

build: the graph deployment ids

---

src/app/api/metrics/abi/context/route.ts

- sort the builders to be used to calculate the ABI

fix: state sync abi

---

.eslintrc.json
src/app/proposals/[id]/page.tsx
src/app/proposals/[id]/types.ts
src/app/proposals/components/action-details/index.tsx
src/app/proposals/components/vote-details/VotingDetails.stories.tsx
src/app/proposals/components/vote-details/VotingDetails.tsx
src/app/proposals/create/CreateProposalHeaderSection.tsx
src/app/proposals/create/TreasuryWithdrawProposalForm.tsx
src/app/proposals/hooks/useGetProposalVotes.ts
src/app/proposals/hooks/useProposalQuorumAtSnapshot.ts
src/app/proposals/hooks/useVoteCast.ts
src/app/proposals/hooks/useVotingPowerAtSnapshot.ts
src/components/ButtonNew/Button.tsx
src/components/Modal/VoteProposalModal.tsx
src/components/NewPopover/index.tsx
src/components/ShortenAndCopy/ShortenAndCopy.tsx
src/components/TypographyNew/Typography.tsx
src/lib/utils/utils.ts
src/shared/hooks/useVoteOnProposal.ts
src/shared/types/index.ts
src/shared/types/types.ts
src/shared/types/voting.ts
src/shared/walletConnection/components/ConnectButtonComponent.tsx
src/shared/walletConnection/types.ts

Implement the design from Figma: https://www.figma.com/design/0WKLa9xs06TsZ1aOtcSNdH/Collective-Redesign---Development?node-id=4749-32943&t=piLJvRclQAAMU3wo-0
- Progress bar and proposal Status
- Proposal description section
- technical details section
- actions section
- Voting Details logic
- NewPopover to account for the rendering logic in the design: https://rsklabs.atlassian.net/jira/software/projects/DAO/boards/88?assignee=633bffbd07a27ebeff18158c%2C61085acf0b454a006804893b&selectedIssue=DAO-1327

DAO-1317 Proposal Details Page

---

src/app/providers/ContextProviders.tsx

Enabled wallet connect in reown app kit to test wallets that support it.

DAO-1215 Enabled wallet connect

---

src/app/builders/BuilderFilterDropdown.tsx
src/app/builders/components/Table/BuilderTable.config.ts
src/app/builders/components/Table/BuildersTable.tsx
src/app/builders/components/Table/Cell/BuilderNameCell/BuilderNameCell.stories.tsx
src/app/builders/components/Table/Cell/BuilderNameCell/BuilderNameCell.tsx
src/app/collective-rewards/utils/isBuilderOperational.ts

TOK-818: improves builder state tooltips

---

src/app/builders/BuilderFilterDropdown.tsx
src/app/builders/components/Table/BuilderTable.config.ts
src/app/builders/components/Table/BuildersTable.tsx
src/app/builders/components/Table/Cell/BuilderNameCell/BuilderNameCell.stories.tsx
src/app/builders/components/Table/Cell/BuilderNameCell/BuilderNameCell.tsx
src/app/builders/components/Table/utils.ts
src/app/collective-rewards/utils/isBuilderOperational.ts

Tok 818/builder status messages

---

src/components/DeltaIndicator/DeltaIndicator.tsx
src/components/Header/AccountAddress.tsx
src/components/Header/BuilderStatus/BuilderStatus.tsx
src/components/Header/BuilderStatus/BuilderStatusView.stories.tsx
src/components/Header/BuilderStatus/BuilderStatusView.tsx
src/components/Header/BuilderStatus/index.ts
src/components/Header/index.ts
src/components/SeparatorBar/SeparatorBar.stories.tsx
src/components/SeparatorBar/SeparatorBar.tsx

top bar builder status
[TOK-825](https://rsklabs.atlassian.net/jira/software/projects/TOK/boards/267?assignee=712020%3A42dabdd3-0b32-4060-be21-62cfd46a1751&selectedIssue=TOK-825)

Tok 825/top bar builder status

---

src/app/builders/components/MultipleSelectDropdown/MultipleSelectDropdown.tsx
src/app/builders/components/Table/BuilderDataRow.tsx
src/app/builders/components/Table/BuilderHeaderRow.tsx
src/app/builders/components/Table/BuilderTable.config.ts
src/app/builders/components/Table/TableColumnDropdown/TableColumnDropdown.stories.tsx
src/app/builders/components/Table/TableColumnDropdown/TableColumnDropdown.tsx
src/app/collective-rewards/rewards/backers/context/BackerRewardsContext.tsx
src/app/collective-rewards/rewards/backers/hooks/useGetBackerRewards.ts
src/app/my-rewards/MyRewardsPage.tsx
src/app/my-rewards/backers/components/BackerRewards/BackerRewards.tsx
src/app/my-rewards/backers/components/BackerRewards/index.ts
src/app/my-rewards/backers/components/Table/BackerRewardsDataRow.tsx
src/app/my-rewards/backers/components/Table/BackerRewardsHeaderRow.tsx
src/app/my-rewards/backers/components/Table/BackerRewardsTable.config.ts
src/app/my-rewards/backers/components/Table/BackerRewardsTable.tsx
src/app/my-rewards/backers/components/Table/BackerRewardsTableContainer.tsx
src/app/my-rewards/backers/components/Table/index.ts
src/shared/context/TableContext/TableActionsContext.tsx
src/shared/context/TableContext/TableContext.tsx

[TOK-793](https://rsklabs.atlassian.net/browse/TOK-793)

TOK-793/backer-rewards-table

---

src/app/my-rewards/builder/components/BuilderRewards.tsx
src/app/my-rewards/builder/components/UpdateBackerRewardModal/UpdateBackerRewardModal.tsx
src/app/my-rewards/builder/components/UpdateBackerRewardModal/UpdateBackerRewardViewModal.stories.tsx
src/app/my-rewards/builder/components/UpdateBackerRewardModal/UpdateBackerRewardViewModal.tsx

Review the UpdateBackerRewards% modal to show if it was already changed
[TOK-832](https://rsklabs.atlassian.net/jira/software/projects/TOK/boards/267/backlog?selectedIssue=TOK-832)

Review the UpdateBackerRewards% modal

---

src/components/MainContainer/headers/HeaderMobile.tsx
src/components/MainContainer/sidebars/SidebarDesktop.tsx
src/components/MainContainer/sidebars/SidebarMobile.tsx
src/components/MainContainer/sidebars/menuData.tsx

DAO-1377 Added menuData for both connected and not connected states

---

src/app/treasury/sections/holders-section/index.tsx

fix from the ticket: https://rsklabs.atlassian.net/browse/DAO-1408

DAO-1408 My Holdings table in Treasury page shows incorrect default sort direction on Holder column

---

src/app/collective-rewards/shared/hooks/useGetABI.ts

- use the top 5 builders to calculate the weighted avg pct

TOK-824: use the top 5 builders to calculate the weighted avg pct

---

src/app/collective-rewards/components/ClaimRewardModal/ClaimRewardsModal.tsx
src/app/my-rewards/backers/components/UnclaimedRewards.tsx
src/app/my-rewards/builder/components/UnclaimedRewards.tsx
src/app/my-rewards/builder/hooks/useGetBuilderUnclaimedRewards.ts

- unifies the backer and builder modal flows in a simple composition

TOK-846: Backer/Builder rewards claim flow

---

src/app/builders/BuildersPage.tsx
src/app/builders/components/BecomeBuilderBanner/BecomeBuilderBanner.stories.tsx
src/app/builders/components/BecomeBuilderBanner/BecomeBuilderBanner.tsx

[The task](https://rsklabs.atlassian.net/browse/TOK-843)

Add the become a builder banner to the Builders page

---

src/app/user/StackingNotifications/StackingNotifications.tsx
src/app/user/StackingNotifications/configs.tsx
src/app/user/StackingNotifications/constants.tsx
src/app/user/StackingNotifications/hooks/useGetBuilderState.tsx
src/app/user/StackingNotifications/hooks/useHasAvailableForBacking.tsx
src/app/user/StackingNotifications/types.ts

- add the banners to be shown under certain conditions
- manually change the cycle data or run it in an env where we control the cycle

TOK-855: add the banners for CR

---

src/app/shared/components/BuilderCard/BuilderCard.tsx
src/app/shared/components/BuildersSpotlight/BuildersSpotlight.tsx
src/app/user/latest-collective/index.tsx

- show random builders in home page
- at the moment it shows the allocation

fix: show random builders in home page

---

src/components/MainContainer/sidebars/SidebarDesktop.tsx
src/components/MainContainer/sidebars/SidebarMobile.tsx

I got this error Each child in a list should have a unique "key" prop. while navigating the app, on the file src/components/MainContainer/sidebars/SidebarDesktop.tsx. It seems that is because the map direct children do not have unique Ids.

fix: sidebar map unique key

---

src/components/IconButton/InfoIconButton.tsx

style: fix tooltip padding

---

src/app/builders/components/Table/BuilderDataRow.tsx
src/app/builders/components/Table/Cell/BuilderNameCell/BuilderNameCell.tsx

fix table row builder cell selected state

style: fix table row builder cell selected state

---

src/components/MainContainer/sidebars/SidebarDesktop.tsx

fix: update unique key for sidebar menu items

---

src/app/delegate/sections/VotingPowerSection/NotConnectedVotingPowerContainer.tsx
src/app/proposals/ProposalsFromChain.tsx
src/app/proposals/ProposalsFromTheGraph.tsx
src/app/proposals/ProposalsSummary.tsx
src/app/proposals/page.tsx
src/shared/walletConnection/constants.tsx

DAO-1423 Added proposals hero and missing total proposals section

---

src/app/user/StackingNotifications/constants.tsx

[TOK-860](https://rsklabs.atlassian.net/browse/TOK-860)

fix: new cycle strarting soon text

---

src/app/backing/components/Metrics/EstimatedRewardsMetric.tsx
src/app/builders/components/ActiveBuilders.tsx
src/app/builders/components/EstimatedRewards.tsx
src/app/builders/components/Metrics.tsx
src/app/builders/components/TotalBacking.tsx
src/app/collective-rewards/components/ActiveBackers/ActiveBackers.tsx
src/app/collective-rewards/components/ActiveBuilders/ActiveBuilders.tsx
src/app/collective-rewards/components/CallToActionSection/CallToActionSection.tsx
src/app/collective-rewards/components/TotalBacking/TotalBacking.tsx
src/app/collective-rewards/shared/hooks/useGetActiveBuildersCount.ts

TOK-866: replace hard-coded metrics with real ones

---

src/app/backing/components/RewardsInfo/RewardsInfo.tsx
src/app/backing/components/Spotlight/Spotlight.tsx
src/components/RifRbtcTooltip/RifRbtcTooltip.tsx

- show the estimated rewards in BuilderCard

fix: show estimated rewards on BuilderCard

---

src/app/communities/nft/[address]/_sections/NftHoldersSection.tsx
src/shared/hooks/useFetchNftHolders.ts

Ticket: [DAO-1432](https://rsklabs.atlassian.net/browse/DAO-1432)

DAO-1432: Incorrect pagination options and holder count mismatch on Community Detail page

---

src/app/builders/components/Table/BuilderHeaderRow.tsx
src/app/my-rewards/backers/components/Table/BackerRewardsHeaderRow.tsx

[TOK-861](https://rsklabs.atlassian.net/jira/software/projects/TOK/boards/267?selectedIssue=TOK-861)

Tok 861/table alignment

---

src/app/proposals/new/components/LeavingProposalModal.tsx
src/app/proposals/new/components/Subfooter.tsx
src/components/Modal/Modal.tsx

[The ticket](https://rsklabs.atlassian.net/jira/software/projects/DAO/boards/88/backlog?assignee=633bffbd07a27ebeff18158c&selectedIssue=DAO-1371)
https://github.com/user-attachments/assets/637cba0d-8ced-455a-be90-1b6729caf39f

DAO-1371 Create Proposal - Leaving prompt

---

src/app/proposals/new/components/VotingPowerWrapper.tsx
src/app/proposals/new/layout.tsx
src/app/proposals/page.tsx
src/components/LoadingSpinner/VotingPowerLoading.stories.tsx
src/components/LoadingSpinner/VotingPowerLoading.tsx
src/components/LoadingSpinner/index.ts
src/shared/walletConnection/types.ts

- Disable "Create a proposal" button:
- Add route protection and automatically redirects to `/proposals` page:

DAO-1427: Add voting power validation to “Create Proposal” button in proposal hero image

---

src/app/shared/components/BuilderCard/BuilderCardControl.tsx

[TOK-869](https://rsklabs.atlassian.net/browse/TOK-869)

TOK-869/remove-action-bar-new-account

---

src/app/builders/components/Table/BuilderDataRow.tsx
src/app/builders/components/Table/BuildersTable.tsx
src/app/builders/hooks/useGetBuilderRewardsSummary.tsx
src/app/collective-rewards/types.ts
src/app/my-rewards/backers/components/Table/BackerRewardsTable.tsx

[TOK-900](https://rsklabs.atlassian.net/browse/TOK-900)

TOK-900/fix-backing-column-builder-table

---

src/app/proposals/components/LatestProposalsTable.tsx
src/app/proposals/components/table-columns/VotesColumn.tsx

DAO-1400: Update “Quorum” column display when proposal table is filtered

---

src/app/backing/BackingPage.tsx
src/app/backing/components/AllocationInput/AllocationInput.tsx
src/app/backing/components/AvailableBackingMetric/AvailableBackingMetric.tsx
src/app/backing/components/TotalBackingMetric/TotalBackingMetric.tsx
src/app/builders/components/Table/BuilderDataRow.tsx
src/app/collective-rewards/components/EstimatedRewards/EstimatedRewards.tsx
src/app/collective-rewards/components/RewardsMetrics/RewardsMetrics.tsx
src/app/collective-rewards/shared/hooks/useGetABI.ts
src/app/collective-rewards/shared/hooks/useGetBackerABI.ts
src/app/home/components/collective-balances-section/index.tsx
src/app/my-rewards/backers/components/Table/BackerRewardsDataRow.tsx
src/app/proposals/[id]/page.tsx
src/app/proposals/new/details/schemas/TokenSchema.ts
src/app/shared/hooks/useGetBuilderEstimatedRewards.ts
src/app/treasury/contexts/TreasuryContext.tsx
src/app/treasury/hooks/useGetTreasuryBucketBalance.ts
src/app/treasury/hooks/useStRifHoldings.ts
src/app/treasury/hooks/useTreasuryTabs.ts
src/app/treasury/types.ts
src/app/user/Balances/BalancesSection.tsx
src/app/user/Balances/balanceUtils.ts
src/app/user/Balances/context/BalancesContext.tsx
src/app/user/Balances/hooks/useGetAddressBalances.ts
src/app/user/Balances/hooks/useGetAddressTokens.ts
src/app/user/Balances/hooks/useGetSpecificPrices.ts
src/app/user/IntroModal/IntroModal.tsx
src/app/user/IntroModal/hooks/useRequiredTokens.ts
src/components/dropdown/data.tsx
src/lib/constants.ts
src/lib/contracts.ts

Ticket: [DAO-1441](https://rsklabs.atlassian.net/browse/DAO-1441)
The key change is in `src/lib/constants.ts`, where the RBTC constant was updated to 'rBTC' following a product requirement.

DAO-1441: rBTC should have lower case "r"

---

src/app/home/components/collective-balances-section/index.tsx

DAO-1456: My Holdings page shows “RIF” label instead of “tRIF” when disconnected in testnet

---

src/app/communities/nft/[address]/_components/AddToWalletButton.tsx
src/app/communities/nft/[address]/utilsClient.ts
src/app/user/Balances/BalanceInfoForUser.tsx
src/shared/utils.ts

Ticket: https://rsklabs.atlassian.net/jira/software/projects/DAO/boards/88/backlog?assignee=633bffbd07a27ebeff18158c&selectedIssue=DAO-1407
@Ken-li-iov the only thing I did not test is adding NFTs, how can I do that? Yes, it touches the same function and we need to test it

DAO-1407 Add “Add to Wallet” functionality for tokens in My Holdings screen

---

src/app/user/Balances/BalanceInfoForUser.tsx

fix: main build

---

src/app/proposals/new/details/activation/page.tsx
src/app/proposals/new/details/components/ProposalInfoSidebar.tsx
src/app/proposals/new/details/components/index.ts
src/app/proposals/new/details/grants/page.tsx

DAO-1404: add info to create proposal pages

---

src/app/proposals/new/components/ProposalSubfooter.tsx
src/app/proposals/new/details/activation/page.tsx
src/app/proposals/new/details/deactivation/page.tsx
src/app/proposals/new/details/grants/page.tsx
src/app/proposals/new/review/activation/page.tsx
src/app/proposals/new/review/deactivation/page.tsx
src/app/proposals/new/review/grants/page.tsx
src/components/MainContainer/ContainerDesktop.tsx
src/components/MainContainer/ContainerMobile.tsx
src/components/MainContainer/LayoutProvider.tsx
src/components/MainContainer/drawers/BottomDrawer.tsx

[TOK-842](https://rsklabs.atlassian.net/jira/software/projects/TOK/boards/267/backlog?assignee=712020%3A42dabdd3-0b32-4060-be21-62cfd46a1751&jql=&selectedIssue=TOK-842)

refactor: unify footer drawer usage

---

src/app/proposals/[id]/page.tsx
src/app/proposals/hooks/useVoteCast.ts
src/app/proposals/hooks/useVotingPowerAtSnapshot.ts

ticket: https://rsklabs.atlassian.net/jira/software/projects/DAO/boards/88/backlog?assignee=633bffbd07a27ebeff18158c&selectedIssue=DAO-1394
https://github.com/user-attachments/assets/9df4f592-b31b-4fea-8d57-fc6b803d598d
https://github.com/user-attachments/assets/aaae366d-238d-4d47-8fc0-5f31cc174b32

DAO-1394 Voting section displays inconsistent state when switching accounts

---

src/app/proposals/new/review/grants/page.tsx

DAO-1455 Show USD amount in grant proposal review page

---

src/app/collective-rewards/allocations/context/AllocationsContext.tsx
src/app/collective-rewards/rewards/backers/context/BackerRewardsContext.tsx
src/app/communities/nft/[address]/CommunityNFTContext.tsx
src/app/proposals/hooks/useGetProposalsWithGraph.ts
src/app/services/getProposalsFromTheGraph.ts

[TOK-913](https://rsklabs.atlassian.net/jira/software/projects/TOK/boards/267?jql=&selectedIssue=TOK-913)
- prefer default values to cast on bigint

TOK-913: Error while loading data from node

---

src/app/collective-rewards/components/BackersCallToAction/BackersCallToAction.tsx
src/app/collective-rewards/components/Banner/Banner.tsx
src/app/collective-rewards/components/BuildersCallToAction/BuildersCallToAction.tsx
src/app/collective-rewards/components/CallToActionCard/CallToActionCard.stories.tsx
src/app/collective-rewards/components/CallToActionCard/CallToActionCard.tsx
src/app/collective-rewards/components/CallToActionSection/CallToActionSection.tsx
src/app/collective-rewards/components/CountMetric/CountMetric.tsx
src/app/collective-rewards/components/CurrentCycle/CurrentCycle.tsx
src/app/collective-rewards/components/CycleMetrics/CycleDay.tsx
src/app/collective-rewards/components/CycleMetrics/CycleEndingOn.tsx
src/app/collective-rewards/components/CycleMetrics/CycleMetrics.tsx
src/app/collective-rewards/components/CycleMetrics/CycleNumber.tsx
src/app/collective-rewards/components/EstimatedRewards/EstimatedRewards.tsx
src/app/collective-rewards/components/RewardsMetrics/RewardsMetrics.tsx
src/app/collective-rewards/components/TotalBacking/TotalBacking.tsx
src/app/collective-rewards/components/TotalRewardsDistributed/TotalRewardsDistributed.tsx
src/app/shared/components/AnnualBackersIncentives/AnnualBackersIncentives.tsx
src/components/MainContainer/ContainerMobile.tsx
src/components/Metric/Metric.tsx
src/components/TokenAmount/TokenAmount.tsx
src/components/TokenAmountDisplay/TokenAmountDisplay.tsx
src/components/TokenImage/TokenImage.tsx
src/components/containers/ActionMetricsContainer.tsx

[TOK-916](https://rsklabs.atlassian.net/jira/software/projects/TOK/boards/267?selectedIssue=TOK-916)

TOK-916: add mobile friendly collective rewards

---

src/app/backing/components/BuilderHeader/BuilderHeader.tsx
src/app/delegate/components/DelegateCard/DelegateCard.tsx

DAO-1486 Fixed DelegateCard.tsx font size.

---

src/app/proposals/new/review/grants/page.tsx
src/lib/contracts.ts

Proposal creation was not being allowed because contract address was not being found.
Now it is.
The issue was a case sensitive search.

DAO-1496 Fixed trbtc proposal creation in dev

---

src/app/my-rewards/backers/components/Table/BackerRewardsTable.tsx

Fix `actionType of undefined` error on my rewards page

fix: actionType of undefined on my rewards page

---

src/app/builders/components/Table/BuilderDataRow.tsx
src/app/builders/components/Table/BuildersTable.tsx

[TOK-907](https://rsklabs.atlassian.net/browse/TOK-907)

TOK-907/table-selection-deactivated-builders

---

src/app/proposals/components/filter/FilterButton.tsx

fix: FilterButton color when filtering

---

src/app/proposals/new/details/grants/page.tsx

fix: Milestone side text

---

src/components/Tooltip/Tooltip.tsx

[TOK-923](https://rsklabs.atlassian.net/browse/TOK-923)

TOK-923: allow tooltip on mobile

---

src/app/proposals/[id]/components/Description.tsx
src/app/proposals/[id]/components/ProgressBar.tsx
src/app/proposals/[id]/components/ProposalDetails.tsx
src/app/proposals/[id]/components/ProposalProggressBar.tsx
src/app/proposals/[id]/components/TechnicalDetails.tsx
src/app/proposals/[id]/components/VotingDetails.tsx
src/app/proposals/[id]/components/index.ts
src/app/proposals/[id]/page.tsx
src/app/proposals/shared/utils.ts

[TOK-895](https://rsklabs.atlassian.net/jira/software/projects/TOK/boards/267?selectedIssue=TOK-895)

TOK-895: split proposal page into smaller components

---

src/app/backing/BackingPage.tsx
src/app/backing/components/AllocationBar/AllocationBarTooltipContent.tsx
src/app/backing/components/BuilderAllocationBar/BuilderAllocationBar.tsx
src/components/Tooltip/Tooltip.tsx

- Change unallocated to available
- remove the builders count from the backing page
- fix allocation bar

TOK-932: Fix minor defects

---

src/app/delegate/components/DelegateCard/DelegateCard.tsx
src/app/delegate/sections/DelegateContentSection/DelegatesContainer.tsx

- Align `DelegateCard` to mobile design
#What:
- Added responsive designs to DelegateCard and the container
https://github.com/user-attachments/assets/fd0b62cc-f137-424a-bf7c-60dd327f1928

DAO-1514 [Mobile] Delegation Page - Cards should be mobile friendly

---

src/app/user/IntroModal/IntroModalContent.tsx

- Button is not aligned to the bottom on the mobile
- Aligned button to the bottom 
https://github.com/user-attachments/assets/bacda509-792d-4698-910a-900ccfee5884
PS: merge after #1381

DAO-1500 [Mobile] Intro Modal - Continue button alignment

---

src/components/Tooltip/Tooltip.tsx

- show tooltips on click on mobile
- on mobile show tooltips always at the bottom

TOK-923: show tooltip on click on mobile

---

src/app/delegate/sections/DelegateContentSection/ConnectedSection.tsx
src/app/delegate/sections/DelegateContentSection/DelegatesContainer.tsx
src/components/Button/Button.tsx
src/components/StackableBanner/BannerContent.tsx

Fix buttons in banners section

---

src/app/builders/components/BecomeBuilderBanner/BecomeBuilderBanner.tsx

[TOK-947](https://rsklabs.atlassian.net/browse/TOK-947?atlOrigin=eyJpIjoiNzYwOTQ1N2E1Y2E5NDU5M2E0NDcyZmM4MjdlOTMyNTYiLCJwIjoiaiJ9)

TOK-947: Add responsive design on Builders banner 

---

src/app/builders/components/ActiveBuilders.tsx
src/app/builders/components/EstimatedRewards.tsx
src/app/builders/components/Metrics.tsx
src/app/builders/components/TotalBacking.tsx
src/components/Metric/Metric.tsx
src/components/Metric/MetricTitle.tsx
src/components/containers/MetricsContainer.tsx

- fix top builders metrics style for mobile and desktop
- add missing usd label to total backing
- uniform metric usage
[TOK-946](https://rsklabs.atlassian.net/jira/software/projects/TOK/boards/267?selectedIssue=TOK-946)

TOK-946: top metrics mobile

---

src/app/treasury/components/MobileHolderCard.stories.tsx
src/app/treasury/components/MobileHolderCard.tsx
src/app/treasury/sections/holders-section/components/HolderCard.tsx
src/app/treasury/sections/holders-section/components/MobileHolderContainer.tsx
src/app/treasury/sections/holders-section/components/index.ts
src/app/treasury/sections/holders-section/index.tsx

DAO-1561 Adjusted treasury holders section to have mobile design

---

src/app/communities/CommunityItem.tsx
src/app/communities/components/ImageDebris.tsx
src/app/communities/components/ResponsiveCommunityItemHOC.tsx
src/app/communities/components/SectionContainer.tsx
src/app/communities/hooks/usePixelExtractor.ts
src/app/communities/page.tsx

DAO-1566 Made community page mobile friendly

---

src/app/proposals/components/LatestProposalsTable.tsx
src/app/proposals/components/ProposalsTableMobile.tsx
src/app/proposals/components/ProposalsTableWithPagination.tsx
src/app/proposals/components/category/Category.tsx
src/app/proposals/components/table-columns/VotesColumn.tsx
src/components/Countdown/Countdown.tsx
src/components/Expandable/Expandable.tsx
src/components/Expandable/ExpandableContent.tsx
src/components/Expandable/ExpandableFooter.tsx
src/components/Expandable/ExpandableHeader.tsx
src/components/Expandable/ExpandableTrigger.tsx
src/components/Status/Status.tsx

DAO-1521: [Mobile] Proposal List Page - Expandable Card

---

src/app/backing/components/AllocationBar/AllocationBar.tsx
src/app/backing/components/AllocationBar/ResizeHandle.tsx
src/components/Modal/Modal.tsx

[TOK-974](https://rsklabs.atlassian.net/browse/TOK-974)

TOK-974/my-balance-slider-overlaps

---

src/app/builders/BuildersPage.tsx
src/app/builders/components/Table/Cell/SelectorCell/SelectorCell.tsx
src/app/builders/components/Table/MobileBuilderRow.tsx
src/components/containers/ActionsContainer.tsx

[TOK-973](https://rsklabs.atlassian.net/jira/software/projects/TOK/boards/267?selectedIssue=TOK-973)
- add animation on builder selection
- disable undesired tooltips in mobile
- fix paddings mobile

TOK-973/animate-builder-selection

---

.env.cr.qa
.env.dao.qa
.env.dev
.env.mainnet
.env.release-candidate-mainnet
.env.release-candidate-testnet
.env.testnet.local
src/app/collective-rewards/shared/actions/fetchABIData.ts

[TOK-969](https://rsklabs.atlassian.net/browse/TOK-969)

TOK-969/subgraph-deployment

---

src/app/proposals/components/LatestProposalsTable.tsx
src/app/proposals/components/filter/useProposalFilters.tsx
src/components/DebounceSearch/DebounceSearch.tsx

DAO-1419: Search bar should always be visible in proposals for mobile

---

src/app/backing/components/BuilderAllocationBar/BuilderAllocationBar.tsx

[TOK-977](https://rsklabs.atlassian.net/browse/TOK-977)

fix(backing): render bar also if no backing
