RootstockCollective/dao-frontend

README.md, package-lock.json, package.json, src/components/Form/Form.tsx, src/index.d.ts, src/pages/proposals/create.tsx
This reverts commit fbbb4f7f8d31db1c2823abf0597d0e084ab01d59.
Will be in conflict until #259 is approved and merged
=> Revert "DAO-686: Add checksum conversion (#225)"

package-lock.json, package.json, src/app/user/Stake/StakingContext.test.tsx, src/app/user/Stake/StakingContext.tsx, src/components/Table/Table.stories.tsx, tsconfig.json, vitest.config.ts, vitest.setup.ts
Fix of UI Rounding error on staking/unstaking amounts . [Details here](https://rsklabs.atlassian.net/browse/DAO-677)
- Install Vitest  + testing-library/react
- write a Vitest crush test (hundreds of repeats with different incoming params) proving that the issue really existed in ~9 % of the cases with the integer (whole) number input.
- patch the StakingProvider 
- now the test is passing
[DAO-677](https://rsklabs.atlassian.net/browse/DAO-677)
=> Fix of UI Rounding error on staking/unstaking amounts

src/app/communities/CommunityItem.tsx
=> fix: tweak css of communities page to closely align with UI design

src/components/MainContainer/MainContainer.tsx
The errors are removed when you navigate from one page to another causing a blank screen if the user is connected to the wrong network. This PR fixes this by checking the network title first. 
I don't particularly like this approach but I don't have the full context of the codebase on why errors are being erased on page change so I didn't want to remove the block. This should be a good alternate.
=> DAO-799 show error of Unsupported Network

src/app/treasury/TokenHoldings.tsx, src/app/treasury/TokenHoldingsStRIF.tsx, src/app/treasury/TreasurySection.tsx
This PR addresses this jira [ticket](https://rsklabs.atlassian.net/browse/DAO-791)
Previous Renders
Current Renders
=> fix: DAO-791 remove unnecessary decimals on the treasury page

src/app/treasury/TreasurySection.tsx
This PR addresses this jira [ticket](https://rsklabs.atlassian.net/browse/DAO-737) 
Current Render
=> fix: implement fix for edge case where balance in rbtc is less that 1e-7

src/components/MainContainer/MainContainer.tsx
- Remove the `useEffect` to clear the message on route change
- We did some testing to check if the message was clear on route change and it worked
- In this [PR](https://github.com/RootstockCollective/dao-frontend/pull/116) we introduced a `useEffect` to clear message on route change that we updated on this [PR](https://github.com/RootstockCollective/dao-frontend/pull/299/files) which clears the messages if it was not the 'Unsupported network'
- [DAO-805](https://rsklabs.atlassian.net/browse/DAO-805)
=> fix: error message on proposal creation not properly displayed

src/app/collective-rewards/actions.ts, src/lib/endpoints.ts
- Move the fetch reward distributed endpoint where are the other endpoints
- include the `chainId` parameter
- the `chainId` is required, otherwise 31 will be used by default
=> chore: move reward distributed endpoint in a single place

src/components/Header/Logo.tsx, src/lib/contracts.ts
makes the Logo component client side only
changes growth bucket back to v1 distributor
This is to prevent
and
=> fix(dao): removes hydration error for Logo

src/app/communities/HolderColumn.tsx, src/app/communities/NftHoldersSection.tsx, src/app/user/Delegation/DelegationSection.tsx, src/app/user/Delegation/hooks/useDelegate.tsx, src/app/user/Delegation/hooks/useGetDelegates.tsx, src/app/user/Delegation/index.ts, src/app/user/page.tsx, src/components/Table/index.ts
=> DAO-823: User wants to see which address have delegated stRIF to "Voting power delegated"

src/pages/proposals/[id].tsx
Note: the image is reflecting the message. When there is a proposal being executed, it'll not show the popup and will always show the button at the right.
=> DAO-679 Fixed proposal confirmation message UI

src/app/user/Delegation/DelegationSection.tsx, src/app/user/Delegation/TokenValue.tsx, src/app/user/Delegation/hooks/useGetDelegates.tsx, src/shared/hooks/useGetExternalDelegatedAmount.tsx
When no power has been received
EDIT: I've added a commit to include a patch after the daily of 11/15/2024 - the voting power delegated table should always show - no matter if there is balance or not. Because else, the user will never be able to reclaim.
=> DAO-824 Added voting power received

src/app/collective-rewards/whitelist/components/Search/WhitelistSearch.tsx
- fix the activated builders filter
=> fix: filter activated builders

src/components/Footer/Footer.tsx, src/components/LeftSidebar/UsefulLinks.tsx, src/components/LeftSidebar/links.tsx
Ticket: https://rsklabs.atlassian.net/jira/software/projects/DAO/boards/88?assignee=633bffbd07a27ebeff18158c&selectedIssue=DAO-852
=> refactor: forum link to menu

src/app/proposals/hooks/useVotingPower.ts
This PR fixes a bug that incorrectly uses an account's voting balance instead of total voting power (balance + delegated) to check if a proposal can be created
=> chore: implement allow account to create proposal once totalVotingPower is sufficient

src/app/user/Delegation/DelegateModal.tsx
Convert the address to lowercase in order to avoid checksum validation
I replicated, using this address `0x623aB477eab37C65e90726F86fD4EBffEB274A47`
=> convert to lowercase to avoid checksum validation

src/components/Modal/BecomeABuilderModal.tsx, src/components/Modal/ProposalSelectionModal.tsx, src/pages/proposals/create.tsx
- Change the submit proposal button to point to the v2 contract
=> fix: change the destination contract for whitelist builder proposal

src/app/collective-rewards/allocations/components/AllocationAmount.tsx, src/app/collective-rewards/allocations/components/AllocationMetrics.tsx, src/app/collective-rewards/allocations/components/BuilderAllocation.tsx, src/app/collective-rewards/allocations/context/AllocationsContext.tsx, src/app/collective-rewards/allocations/context/allocationsActions.tsx, src/app/collective-rewards/allocations/page.tsx
- disables save allocs when:
- the amount to allocate is bigger than balance
- the cumulative amount is bigger than balance
- allocation didn't change
- fixes the allocationsCount value
- renames totalAllocations to amountToAllocate as it was confusing
=> fix: disable save allocs and other goodness

src/app/collective-rewards/rewards/backers/BackerRewardsTable.tsx, src/app/collective-rewards/rewards/backers/hooks/useGetBackerRewards.ts, src/app/collective-rewards/rewards/utils/getPercentageData.ts
- filter out builders without allocations or available rewards for the backer
=> fix: filter out builders without allocations or rewards

src/app/collective-rewards/leaderboard/BuildersLeaderBoardTable.tsx
What
- fix: leaderboard crash when sort per reward
- chore: improve ux by sort descendent allocations
[Jira Ticket](https://rsklabs.atlassian.net/jira/software/projects/TOK/boards/267?selectedIssue=TOK-504&text=crash)
=> Tok 504/fix sort leaderboard per rewards crash

src/app/collective-rewards/allocations/components/BuilderAllocation.tsx, src/app/collective-rewards/allocations/context/AllocationsContext.tsx, src/app/collective-rewards/allocations/hooks/useBackerTotalAllocation.ts, src/app/collective-rewards/allocations/hooks/useBuildersWithBackerRewardPercentage.ts, src/app/collective-rewards/rewards/builders/hooks/useGetBuildersRewards.ts, src/app/collective-rewards/types.ts
Resolves https://rsklabs.atlassian.net/browse/TOK-502?focusedCommentId=86848
by fetching both backer rewards and the currently active rewards percentage
it also simplifies the context and its hook dependencies by not combining everything with builders
=> TOK-502: use active backer rewards percentage

src/app/collective-rewards/shared/components/Table/TableCells.tsx
what: align builder icon vertically
=> chore: leaderbord align builder icon vertically

src/app/collective-rewards/rewards/builders/ClaimableRewards.tsx, src/app/collective-rewards/rewards/builders/Rewards.tsx, src/app/collective-rewards/rewards/builders/hooks/useClaimBuilderRewards.ts, src/app/collective-rewards/rewards/components/ClaimYouRewardButton.tsx
[TOK-517](https://rsklabs.atlassian.net/browse/TOK-517)
[Depends on](https://github.com/RootstockCollective/dao-frontend/pull/430)
=> TOK-517: pause builder reward claim

src/app/collective-rewards/allocations/hooks/index.ts, src/app/collective-rewards/allocations/hooks/useValidateBackerAllocations.ts, src/app/collective-rewards/leaderboard/BuilderLeaderBoard.tsx, src/app/collective-rewards/rewards/MyRewards.tsx, src/app/collective-rewards/rewards/components/Section/RewardsSectionHeader.tsx
- Disable manage allocation button when there is no selection or allocation done by the backer.
=> TOK-538: disable manage allocations button

src/app/collective-rewards/rewards/backers/hooks/useGetGaugesBackerRewardsClaimed.ts, src/app/collective-rewards/rewards/builders/hooks/useGetBuildersRewards.ts, src/app/collective-rewards/rewards/hooks/useGetGaugesEvents.ts, src/app/collective-rewards/rewards/hooks/useGetGaugesNotifyReward.ts
- Fix the loading state when getting events from all the gauges
- Fix the last cycle rewards from the leaderboard since it needs to show the backers rewards
=> fix: events loading and last cycle backer rewards

src/app/collective-rewards/allocations/components/Header.tsx, src/app/collective-rewards/leaderboard/BuilderLeaderBoard.tsx, src/app/collective-rewards/leaderboard/BuildersLeaderBoardTable.tsx, src/app/collective-rewards/metrics/TotalAllocationsMetrics.tsx, src/app/collective-rewards/rewards/MyRewards.tsx, src/app/collective-rewards/rewards/backers/BackerRewardsTable.tsx, src/app/collective-rewards/rewards/backers/ClaimableRewards.tsx, src/app/collective-rewards/rewards/backers/Rewards.tsx, src/app/collective-rewards/rewards/builders/ClaimableRewards.tsx, src/app/collective-rewards/rewards/builders/EstimatedRewards.tsx, src/app/collective-rewards/rewards/components/Tooltip.tsx, src/app/collective-rewards/shared/components/CRWhitepaperLink.tsx, src/app/collective-rewards/shared/components/Table/TableHeaders.tsx, src/app/collective-rewards/shared/components/index.ts
=> TOK-536: update text and tooltips

src/app/collective-rewards/metrics/Metrics.tsx, src/app/collective-rewards/metrics/TotalActiveBuildersMetrics.tsx, src/app/collective-rewards/metrics/TotalAllocationsMetrics.tsx, src/app/collective-rewards/metrics/components/ABIMetrics/ABIMetrics.tsx, src/app/collective-rewards/metrics/components/ABIMetrics/hooks/useGetABI.ts, src/app/collective-rewards/metrics/components/ABIMetrics/index.ts, src/app/collective-rewards/metrics/hooks/useGetTotalAllocation.ts, src/app/collective-rewards/rewards/MyRewards.tsx, src/app/collective-rewards/rewards/backers/ClaimableRewards.tsx, src/app/collective-rewards/rewards/backers/hooks/useGetBackerRewards.ts, src/app/collective-rewards/rewards/builders/EstimatedRewards.tsx, src/app/collective-rewards/rewards/builders/hooks/useGetBuildersRewards.ts, src/app/collective-rewards/types.ts, src/app/collective-rewards/utils/isBuilderOperational.ts, src/components/Popover/Popover.tsx
=> TOK-541: add ABI

src/app/communities/communityUtils.tsx
We're hiding the claim button for OG Founders for all environments as in mainnet we no longer have NFTs available to be minted. Although the correct implementation would be comparing when the user staked stRIF to the requirement date. Let's keep simple for now.
=> DAO-807: Hide claim button for OG Founders

src/app/proposals/create/TreasuryWithdrawProposalForm.tsx, src/lib/utils.ts
=> DAO-945 Will show 0 when USD is NaN

src/app/collective-rewards/settings/builder/BuilderRewardsSettingsForm.tsx
- utilises fully [react-number-format](https://s-yadav.github.io/react-number-format/docs/numeric_format) lib
- removes validation with zod as the above renders it "impossible" to enter wrong values
https://rsklabs.atlassian.net/browse/TOK-555
=> TOK-555: format backers reward input field

src/app/collective-rewards/allocations/context/AllocationsContext.tsx, src/app/collective-rewards/allocations/context/utils.test.ts, src/app/collective-rewards/allocations/context/utils.ts, src/app/collective-rewards/allocations/hooks/useAllocateVotes.test.tsx, src/app/collective-rewards/allocations/hooks/useAllocateVotes.ts, src/app/collective-rewards/allocations/page.tsx, src/app/collective-rewards/user/components/Button/BecomeABuilderButton.test.tsx
[TOK-565](https://rsklabs.atlassian.net/browse/TOK-565)
=> TOK-565/votes-allocation-gas-consumption

src/config/config.ts
- batch multiple requests when possible
- to reduce the number of http requests made by the dapp
- [wagmi batch](https://wagmi.sh/core/api/transports/http#batch)
=> TOK-594: batch multiple requests

src/app/proposals/choose/components/info-panel/data.tsx
Correct the URLs in the info panel data to direct users to the appropriate pages for grant proposals and the governance forum.
=> Update link URLs in info panel for grant proposals and governance forum

src/components/Modal/VoteSubmittedModal.tsx
The proposal vote submitted modal was using wrong data for the proposal name.
This PR fixes that.
[Task](https://rsklabs.atlassian.net/browse/TOK-603)
> [!NOTE]
> Did not refactor as the whole component needs improvement (eg [proposal type](https://github.com/RootstockCollective/dao-frontend/blob/ce830ff37a269dfd109aeea2650333ccb5ef4733/src/components/Modal/VoteSubmittedModal.tsx#L12))
=> TOK-603: fix wrong modal data

src/app/collective-rewards/rewards/backers/Rewards.tsx
All time share metric is removed until RBI% is introduced.
[Task](https://rsklabs.atlassian.net/browse/TOK-610)
=> TOK-610: temp remove backers all-time share

src/config/ipfsGateways.ts
Eliminate the use of a deprecated IPFS gateway URL from the configuration.
=> Remove deprecated IPFS gateway URL

src/app/user/Balances/actions.ts, src/config/index.ts, src/config/ipfsGateways.ts, src/lib/constants.ts
Simplify IPFS URI fetching by using a single gateway constant instead of multiple gateways. This change will ensure the use of only one reliable IPFS node.
=> Replace IPFS gateways list with a single one

src/app/proposals/choose/components/info-panel/arrow-link.tsx, src/app/proposals/choose/components/info-panel/deactivation-footer.tsx, src/app/proposals/choose/components/info-panel/info-panel.tsx
Update the deactivation URL to use an internal link and refactor the ArrowLink component to accept additional props and improve its functionality.
https://rsklabs.atlassian.net/browse/DAO-1045
=> Change deactivation URL to internal link and refactor ArrowLink component

src/components/Alert/Alert.tsx
- when showing errors, wrap long words if needed
- the error is shown out of margins.
=> TOK-624: wrap long words if needed

src/app/collective-rewards/leaderboard/BuildersLeaderBoardTable.tsx, src/components/Address/AddressOrAlias.tsx
- fix the builder name in the leaderboard table
- the popover text is hidden
- the copy button is hidden
=> TOK-638: show overflow and break the word if long

src/app/user/Balances/context/BalancesContext.tsx
The solution to be too simple to be true, but I verified with a couple of Stack Overflow threads, looks solid.
=> refactor: make sure that balances and prices change independently

src/app/user/Delegation/DelegateModal.tsx
Add scroll bar to the delegate modal when displaying shepherds dataset larger than 5 items.
- More than 5 items:
- Exactly five items and less (no scrollbar):
[DAO-1079](https://rsklabs.atlassian.net/browse/DAO-1079)
=> Add scrollable container to DelegateModal table

src/app/shared/components/NFTBoosterCard/SelfContainedNFTBoosterCard.tsx
Hotfix for the nft booster card to display the thumbnail.
=> TOK-648: show nft thumb in boost card

src/app/user/Delegation/DelegateModal.tsx
Change the delegation modal behavior and appearance:
- show scrollbar only if the number of shepherds is more than 5
- change the scrollbar background color
Requested by the tickets 
- [Num shepherds](https://rsklabs.atlassian.net/browse/DAO-1126)
- [Color](https://rsklabs.atlassian.net/browse/DAO-1133)
=> fix: show delegation modal scrollbar only for more than 5 shepherds

.github/scripts/nft_boost/activateBoost.ts, .github/scripts/nft_boost/process.utils.ts, .github/workflows/booster.yaml
Lowercase the nft address only in the script
> ![IMPORTANT]
> lowecase backer addresses, as well, for the next release
To not break the currently implemented logic in v1.6.0
=> TOK-655: lowercase addresses in gen data

src/components/Link/ExternalLink.tsx, src/components/Link/types.ts, src/components/section-header/index.tsx
Now you can use `SectionHeader` custom component for your sections as well. This will allow us not to modify use cases but rather just the component itself(for example when it becomes collapsable).
=> feat: SectionHeader reusable component

src/components/Alert/Alert.tsx
- fix max height to error paragraph
- to avoid that an error content fill the whole page
=> fix: set max height to paragraph

src/app/collective-rewards/settings/Settings.tsx
- wait until the builder info is ready before redirecting
- otherwise the Builder won't be able to access the page
=> fix: wait until the data is ready before redirecting

src/app/proposals/[id]/page.tsx, src/app/proposals/components/LatestProposalsTable.tsx, src/app/proposals/components/table-columns/ProposalNameColumn.tsx
https://rsklabs.atlassian.net/browse/DAO-1124
1. Remove category column
2. Remove Arrow for proposal name
3. If the user goes to a proposal that is successful or on queue, should display the correct button “Put to queue” or “Execute” and prompt the disclaimer, same as vote does
=> DAO-1124: remove proposal category, remove arrow icon, and include proposal states

src/app/communities/nft/[address]/CommunityNFTContext.tsx, src/app/communities/nft/[address]/_sections/MembershipNFTSection.tsx, src/app/communities/nft/[address]/_sections/UserMemberSection.tsx
Fixed add to wallet width when description exists
Brought back tokens available as it was removed per design when it was not supposed to
Fixed claim it button - was missing isMintable in the context
=> DAO-1155 fix add to wallet button

src/app/communities/nft/[address]/_sections/NftHoldersSection.tsx
This PR fixes the bug reported in this [ticket](https://rsklabs.atlassian.net/browse/DAO-1147)
Previous Render(rns domain not displayed)
Current Render(rns domain displayed)
=> feat: display rns domain in grid view

src/components/Label/GlowingLabel.tsx
Fix header (title) appearance in GlowingLabel component. Make the header text color white when glow modifiers are not applied (previously it was green)
Requested by [QA in the ticket](https://rsklabs.atlassian.net/browse/DAO-1162)
=> Refactor style handling in GlowingLabel component

src/config/config.ts, vitest.config.ts
- instantiates the wagmi network configuration with only the network required by the current environment.
- adds env vars to vitest config to avoid issues in tests
Resolves [bug](https://rsklabs.atlassian.net/browse/TOK-675).
=> fix(cr): disable hooks when no wallet

src/app/user/Delegation/DelegateModal.tsx, src/components/Modal/ConfirmationModal.tsx, src/components/Modal/Modal.tsx
https://github.com/user-attachments/assets/f93a2249-fe70-461c-81ea-e8a0141ba875
the addresses of shepherds was uppercase addresses whereas in the rest of the dApp they are lowercase
added lowercasing when we set address
While searching found minor code readability issue with optional dependencies preceding required.
=> DAO-1134 Delegation address mismatch

src/app/treasury/TabsSection.tsx, src/app/user/page.tsx
Introduce layout IDs for UnderlineTabs components on different pages 
Without being identified, animated elements (underlines) jump from User page to Treasury page and other way around
=> fix: tabs underline interferance

src/app/communities/nft/[address]/_sections/NftHoldersSection.tsx
This PR addresses this jira [ticket](https://rsklabs.atlassian.net/browse/DAO-1200)
Previous Renders
Current Renders of OG partners and Beta builders when they have 0 holders
=> fix: don't show holders section at all for community with 0 holders

src/app/communities/nft/[address]/_sections/NftHoldersSection.tsx
This PR addresses an additional bug reported on this [ticket](https://rsklabs.atlassian.net/browse/DAO-1200) which was initially fixed by this [PR](https://github.com/RootstockCollective/dao-frontend/pull/929)
**Bug**
When you move between different communities pages, the holders section list experience a slight lag where it updates that section from the previous list to the correct current list of the active community. And then in the case of a community with no holder, this incorrectly still renders the holders section showing an error.
Fixed inconsistent rendering behaviour when navigating between pages with and without NFT holders. The component now properly handles state transitions and prevents showing stale data or error messages.
**Changes**
Added tracking for address changes to …
=> fix: fix issue causing lag in loading data/incorrect data for holders section

src/app/proposals/hooks/useRemoveBuilderProposal.ts
Changes the SC target address for the dewhitelist call from backers manager to builder registry, where this function now resides
Resolves [TOK-717](https://rsklabs.atlassian.net/browse/TOK-717)
=> TOK-717: change target SC addr for dewhitelist

src/app/proposals/components/LatestProposalsTable.tsx, src/app/proposals/components/table-columns/StatusColumn.tsx, src/app/proposals/hooks/useProposalListData.ts, src/components/Status/Status.stories.tsx, src/components/Status/Status.tsx, src/components/Status/types.ts, src/theme/base.css, src/theme/default.css
Refactor and redesign Proposal Status labels (Status component)
This pull request refactors the handling of proposal states across the codebase by replacing string-based states with a strongly-typed `ProposalState` enum. It simplifies the logic for mapping proposal states to UI components, improves type safety, and enhances maintainability. Additionally, it introduces a new color variable for better visual representation of the "Active" state.
For the redesigned proposals list page
[DAO-1312](https://rsklabs.atlassian.net/browse/DAO-1312)
=> feat: update status labels with new design

src/app/backing/BackingPage.tsx, src/app/backing/components/AllocationBar/AllocationBarSegment.tsx, src/app/backing/components/AllocationInput/AllocationInput.tsx, src/app/backing/components/BuilderAllocationBar/BuilderAllocationBar.tsx, src/app/backing/components/CurrentBacking/CurrentBacking.tsx, src/app/backing/components/Spotlight/Spotlight.tsx, src/app/backing/components/StickySlider/StickySlider.tsx, src/app/builders/components/Table/BuildersTable.tsx, src/app/shared/components/BuilderCard/BuilderCard.tsx, src/app/shared/components/BuilderCard/BuilderCardControl.tsx
- add builder proposal link to Builder card
- show the selected builders
- add animation on editing
- manage drawer according to the allocation change
- add stake redirection
- show the spotlight without title if user is not connect or they already allocated
- change the usd formatting in the allocation input
- truncate builder name
=> TOK-838: Allocation bar adjustments

src/app/backing/components/AllocationBar/AllocationBar.tsx, src/app/backing/components/AllocationBar/AllocationBarDragHandle.tsx, src/app/backing/components/AllocationBar/AllocationBarResizeHandle.tsx, src/app/backing/components/AllocationBar/AllocationBarSegment.tsx
[TOK-875](https://rsklabs.atlassian.net/jira/software/projects/TOK/boards/267?selectedIssue=TOK-875)
- show tooltip with percentages for small segments 
- more exactly, when 2 neighbor's sum is small
- move separator between bar segments, according to the design
- remove 3 dots, and allow the whole bar to drag segment
Still awaiting Vlad confirmation on the changes
=> Tok 875/allocation bar overlaps and style

src/app/builders/components/Table/BuilderDataRow.tsx, src/app/my-rewards/backers/components/Table/BackerRewardsDataRow.tsx
Instead of rendering different components on hover, we change tailwinds classes to show/hide the cell
=> TOK-908: removes tables sticky selection

src/app/user/StackingNotifications/StackingNotifications.tsx
Fixed flickering issue with stacking banners on the home screen that occurred approximately every minute after user connection.
The banner component was returning `null` during dependency loading checks on every polling cycle (every ~60 seconds), causing the DOM element to unmount and remount, resulting in visible flickering.
The root cause was the `areDependenciesLoaded` check that blocked rendering not just on initial load, but also during subsequent data polling updates.
- Added `hasLoadedOnce` state to track initial load completion
- Modified loading logic to only return `null` before the first successful render
- After initial load, component continues rendering even during polling updates
- Maintains live data updates while preventing visual flickering
[Resolves: Stacking Banner …
=> Prevent stacking banner flickering on home screenre rendering before initial data load

next.config.mjs, package.json
- Added Turbopack support for development mode
- Created separate webpack development script for stability
- Updated Cypress E2E tests to use webpack mode
- Turbopack provides significantly faster development experience with faster hot reloads and compilation
- Webpack fallback ensures compatibility with custom webpack configurations and stable testing environment
- Separate scripts allow developers to choose between speed (Turbopack) and stability (webpack) based on their needs
- Modified `dev` script to use `--turbo` flag for Turbopack
- Added `dev:webpack` script for traditional webpack development
- Updated Cypress test scripts to use `dev:webpack` for reliable E2E testing
- Removed experimental Turbopack configuration (not needed in Next.js 15)
=> feat: add Next.js Turbopack support with webpack fallback

src/app/communities/components/SectionContainer.tsx, src/app/user/my-holdings/MyActivityAndBalances.tsx, src/app/user/my-holdings/hooks/useIsBuilder.ts
[TOK-874](https://rsklabs.atlassian.net/jira/software/projects/TOK/boards/267?selectedIssue=TOK-874)
According to the US updates, content show always display as long as there is a connected user.
I just removed a TODO, and shows the title conditionally if the user is a backer, or a builder.
=> TOK-874: show proper title for builder and backer

src/components/MainContainer/sidebars/usefulLinksData.tsx
=> DAO-1466: Useful Links - the spacing between Get RIF/rBTC and icons needs to be larger

src/app/user/latest-collective/components/CreatorRowComponent.tsx, src/app/user/latest-collective/components/LatestProposalCard.tsx
- The design wants the cards to be as tall as the longest title with spacing
- adjust the styling to make sure of that
- Now the address is orange not "by"
- the by {address} and date is no longer spanning 2 lines
- closes 3 tickets: https://rsklabs.atlassian.net/jira/software/projects/DAO/boards/88/backlog?assignee=633bffbd07a27ebeff18158c&selectedIssue=DAO-1469, https://rsklabs.atlassian.net/jira/software/projects/DAO/boards/88/backlog?assignee=633bffbd07a27ebeff18158c&selectedIssue=DAO-1470 and https://rsklabs.atlassian.net/jira/software/projects/DAO/boards/88/backlog?assignee=633bffbd07a27ebeff18158c&selectedIssue=DAO-1475
=> DAO-1469, DAO-1470, DAO-1475

src/app/user/IntroModal/IntroModalContent.tsx, src/components/Icons/CloseIconKoto.tsx, src/components/Modal/Modal.tsx
- Align with the design
- Use newly created close Icon in the Modal component
=> DAO-1498 [Mobile] Intro Modal - Close icon is different

src/app/proposals/components/LatestProposalsTable.tsx, src/components/MainContainer/ContainerMobile.tsx, src/shared/hooks/index.ts, src/shared/hooks/useStickyHeader.ts
- Make Latest Proposals search and filter bar sticky when scrolled past on mobile
- Ticket: https://rsklabs.atlassian.net/jira/software/projects/DAO/boards/88/backlog?assignee=633bffbd07a27ebeff18158c&selectedIssue=DAO-1525
- `useStickyHeader` hook to bypass issues with CSS layout and to apply to any Header we wish
- Applied to Latest Proposals bar
https://github.com/user-attachments/assets/d7a26a6c-d67f-4693-b703-300b637890c7
=> DAO - 1525 [Mobile] Proposal List Page - Latest Proposals Header should scroll with user (sticky)

src/app/delegate/components/VotingPowerContainer/VotingPowerCard.tsx, src/app/proposals/ProposalsFromTheGraph.tsx, src/app/proposals/ProposalsSummary.tsx
- Implement Active Proposals on `ProposalSummary`
- Adjust to mobile design
- Ticket: https://rsklabs.atlassian.net/jira/software/projects/DAO/boards/88/backlog?assignee=633bffbd07a27ebeff18158c&selectedIssue=DAO-1522
- Add Active proposals count `VotingPowerCard`
- Change labels and layout based on the platform
- Render `ConnectWallet` button
=> DAO-1522 [Mobile] Proposal List Page - Edit ProposalsSummary to adapt to mobile

src/app/user/Stake/Steps/StepOne.tsx
=> DAO-1576: [Mobile] Available amount text overlaps buttons in staking/unstaking modal with long decimals
